### ISSUE TITLE
User Initial Location

### ISSUE THREAD

**Issue by mehdi-belhaj** [mehdi-belhaj/weather-app#3]
### Purpose:
Get the Initial Location of the user and use it to display the weather information of his city.

### Tasks List:
- [x] Use the `navigator.geolocation` API to get the user's coordinates (_latitude_, _longitude_).
- [x] Use **OpenCage Geocoding** API to get the user's city (address, country...) from the coordinates.
- [x] Use the city name as parameter of  `weather.fetchWeather();`.
- [ ] Fix the bug when the user enters a city name that doesn't exist.

**Comment by andrewkykoo** [comment]
@mehdi-belhaj I would like to work on this issue. Thanks.
